### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by aaronransley** [hashchange/jquery.documentsize#1]
This is a great tool with excellent documentation. It solved a long-time problem I've been having a surprising amount of trouble finding a solution to: effective viewable height vs. viewport / screen height on Mobile Safari.

Many cheers. Would donate if a link were available :moneybag:

**Comment by hashchange** [comment]
Hey, thank you for the kind words! Glad it was helpful. Also, thanks for suggesting a donation link - it had never occurred to me to put one there, now I'll look into it.

If there were a prize for opening the perfect Github issue, you'd win flat out :)

Cheers, Michael
