### ISSUE TITLE
jquery.documentsize + IE9 and window.onload not firing until mouse move

### ISSUE THREAD

**Issue by u01jmg3** [hashchange/jquery.documentsize#3]
Hello, I've just sourced a strange scenario whereby IE9 does not fire the window.onload event until the mouse is moved when documentsize is included on the page. Remove the library and the problem goes away. I can provide a video of the behaviour if required. Do you know what could be wrong?

**Comment by hashchange** [comment]
Thanks for your input. I can't reproduce the problem, though. Have a look at this minimal test page in IE9:

http://jsbin.com/hejopi/1 (Code view: http://jsbin.com/hejopi/1/edit?html,js,output )

Works as expected. Can you provide a code sample on JSBin or Codepen to reproduce the error? (Please boil your code down to the bare essentials - thanks!)

**Comment by u01jmg3** [comment]
I've been trying to reduce my code to have a bare essentials 'broken' version to demonstrate the issue but each time I try to remove code the problem becomes less frequent or disappears altogether. I have started by reducing HTML content first but the same pattern emerges. The same is true when I start by reducing JavaScript content first. Cannot seem to reduce my code to the bare essentials because it disrupts being able to replicate the issue.

Would the amount of page content affect the work documentsize has to do?

Here is a GIF of the issue in action (5.12 MB):

![demo](https://cloud.githubusercontent.com/assets/1266205/12677617/1fd28c96-c692-11e5-8ed4-e0f18311e864.gif)

**Comment by hashchange** [comment]
That's weird. The amount of code shouldn't matter one bit. Maybe something else is going on. Have you seen [this answer on SO](http://stackoverflow.com/a/12924439/508355)?

I'm not sure I can figure out if jQuery.documentSize plays a role in it unless I have some code which allows me to reproduce the issue. Let me know if you can come up with something, and I'll have a look.

**Comment by u01jmg3** [comment]
Tried out the suggestion on SO with adding the `window.console` code but to no avail.

I've put some code online which has the problem in IE9:
- http://homepages.abdn.ac.uk/jonathan.goode/pages/search/search.php/undergraduate/degree-programmes?lite
  - http://homepages.abdn.ac.uk/jonathan.goode/pages/search/assets/scripts/all.min.js

I was using Browserstack for IE9

Let me know what else I can help with

**Comment by hashchange** [comment]
Good news! I have cloned your environment and found a fix. For IE9, the feature test is run on demand now, rather than on DOM ready. That does the trick.

I have also tested your code against IE8, 10 and 11, and a host of other browsers. No load event issues there.

**Comment by u01jmg3** [comment]
Impressive work. Hat off to you, Sir :)

Just to clarify, I can confirm the IE9 issue has gone!

**Comment by hashchange** [comment]
Glad to see that it works. Thanks for your feedback!
