### ISSUE TITLE
$.windowHeight("visual") value is still affected by the mobile safari url and tab bar

### ISSUE THREAD

**Issue by timothyachumba** [hashchange/jquery.documentsize#6]
Hi there, correct me if I'm wrong but isn't `$.windowHeight("visual")` suppose to prevent the changing window height on mobile browsers?

I may have implemented this wrong, can you help?

Thanks

**Comment by hashchange** [comment]
I'm not sure if I understand your issue correctly, but let me try. The height of the visual viewport in mobile browsers changes - and there is nothing anyone can do about it - when the user scrolls and the browser switches to minimal UI (hiding the URL and tab bar). That behaviour is solely under the control of browser vendors and not exposed to Javascript.

What the `$.windowHeight()` method should do - and hopefully does - is to report the actual current height of the visual viewport. In other words, the return value should reflect whether or not the browser is in minimal UI, and therefore _should_ change as soon the URL and tab bar are hidden.

Does that clarify the behaviour you are seeing? I am going to close this issue now, but please feel free to reopen it in case I got you wrong.
